name: test
on: [push]
jobs:
  build:
    name: Test Guix packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/guix
          # use a key that (almost) never matches
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      # Cannot use a cache for /gnu/store, since restore fails
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Build packages
        run: guix package -L . -A | grep r0man/packages | awk '{print $1}' | xargs guix build -L .
