name: test
on: [workflow_dispatch]
jobs:
  build:
    name: Test VM runner
    runs-on: [self-hosted, docker]
    steps:
      - name: Runner environment
        run: uname -a && docker version
      - name: Docker in the VM
        run: docker run --rm hello-world
